import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

export const useLanguage = () => useContext(LanguageContext);

const translations = {
    he: {
        // Layout & Navigation
        appName: 'Farm Manager',
        smartFarm: 'ניהול חווה חכם',
        main: 'ראשי',
        dashboard: 'לוח בקרה',
        fieldsAndCrops: 'שדות וגידולים',
        fields: 'שדות',
        crops: 'גידולים',
        agriculturalOps: 'פעולות חקלאיות',
        sheepFlock: 'עדר כבשים',
        sheep: 'כבשים',
        vaccinations: 'חיסונים',
        medicalTreatments: 'טיפולים רפואיים',
        births: 'לידות',
        waterAI: 'ניהול מים - AI',
        waterOverview: 'סקירת מים',
        waterReadings: 'קריאות מים',
        aiPredictions: 'תחזיות AI',
        anomalies: 'חריגות',
        admin: 'מנהל',
        farmManager: 'מנהל חווה',
        employee: 'עובד',
        user: 'משתמש',
        logout: 'התנתקות',
        lightMode: 'מצב בהיר',
        darkMode: 'מצב כהה',

        // Dashboard
        hello: 'שלום',
        farmer: 'חקלאי',
        dashboardSummary: 'הנה סיכום המצב בחווה שלך היום',
        totalFields: 'שדות',
        active: 'פעילים',
        growing: 'בצמיחה',
        waterThisMonth: 'מ״ק מים החודש',
        openAnomalies: 'חריגות פתוחות',
        upcomingVacc: 'חיסונים קרובים',
        waterTrend30: 'מגמת צריכת מים (30 יום אחרונים)',
        details: 'פרטים',
        flockHealth: 'מצב בריאות העדר',
        healthy: 'בריאים',
        sick: 'חולים',
        pregnant: 'בהריון',
        recentOps: 'פעולות אחרונות',
        all: 'הכל',
        date: 'תאריך',
        field: 'שדה',
        opType: 'סוג פעולה',
        status: 'סטטוס',
        planting: 'שתילה',
        harvesting: 'קציר',
        fertilizing: 'דישון',
        spraying: 'ריסוס',
        irrigation: 'השקיה',
        plowing: 'חרישה',
        weeding: 'ניכוש',
        completed: 'הושלם',
        noRecentOps: 'אין פעולות אחרונות',
        alerts: 'התראות',
        upcomingVaccAlert: 'חיסון קרוב',
        sheepTag: 'כבש',
        sickSheep: 'כבשים חולים',
        sickSheepDesc: 'דורשים טיפול וביקורת וטרינרית',
        waterAnomalies: 'חריגות מים',
        waterAnomaliesDesc: 'נדרשת בדיקה של צריכת מים חריגה',
        pregnantSheep: 'כבשים בהריון',
        pregnantDesc: 'מעקב שוטף נדרש',
        noAlerts: 'אין התראות חדשות',
        waterConsumption: 'צריכת מים (מ״ק)',

        // Weather
        currentWeather: 'מזג אוויר נוכחי',
        temperature: 'טמפרטורה',
        humidity: 'לחות',
        wind: 'רוח',
        rain: 'גשם',
        feelsLike: 'מרגיש כמו',
        noWeatherData: 'אין נתוני מזג אוויר',

        // Water Dashboard
        smartWaterMgmt: 'ניהול מים חכם',
        aiWaterSystem: 'מערכת AI מתקדמת לאופטימיזציה של צריכת המים בחווה',
        aiEnabled: 'AI מופעל',
        totalConsumption: 'סה״כ צריכה (מ״ק)',
        minimum: 'מינימום',
        maximum: 'מקסימום',
        avgPerReading: 'ממוצע לקריאה',
        readings: 'קריאות',
        openAnomaliesCount: 'חריגות פתוחות',
        outOf: 'מתוך',
        total: 'סה״כ',
        expectedSavings: 'חיסכון צפוי',
        withAIPredictions: 'בעזרת תחזיות AI',
        waterTrend: 'מגמת צריכת מים',
        last30Readings: '30 הקריאות האחרונות',
        allReadings: 'כל הקריאות',
        anomalyDistribution: 'התפלגות חריגות',
        anomaliesDetected: 'חריגות זוהו',
        noData: 'אין נתונים להצגה',
        noAnomalies: 'אין חריגות',
        weeklyPattern: 'דפוס צריכה שבועי',
        avgByDay: 'ממוצע צריכה לפי ימים',
        aiInsights: 'תובנות AI',
        autoAnalysis: 'ניתוח אוטומטי',
        leadingAlgo: 'אלגוריתם מוביל',
        confidenceLevel: 'רמת ביטחון',
        avgConsumption: 'ממוצע צריכה',
        analyzedReadings: 'קריאות מנותחות',
        anomaliesNeedAttention: 'חריגות דורשות טיפול',
        checkAnomalies: 'יש לבדוק ולטפל בחריגות',
        potentialSavings: 'חיסכון פוטנציאלי',
        basedOnAI: 'על בסיס תחזיות AI',
        manageReadings: 'נהל קריאות מונים',
        smartAlgorithms: '3 אלגוריתמים חכמים',
        allOk: 'הכל תקין!',
        openAnomaliesText: 'חריגות פתוחות',
        latestPredictions: 'תחזיות אחרונות',
        aiWaterPredictions: 'תחזיות AI לצריכת מים',
        allPredictions: 'כל התחזיות',
        confidence: 'ביטחון',
        cubicMeters: 'מ״ק',
        highConsumption: 'צריכה גבוהה',
        lowConsumption: 'צריכה נמוכה',
        leakSuspected: 'חשד לדליפה',
        sensorError: 'שגיאת חיישן',
        avgDailyConsumption: 'ממוצע צריכה יומית',
        sunday: 'ראשון',
        monday: 'שני',
        tuesday: 'שלישי',
        wednesday: 'רביעי',
        thursday: 'חמישי',
        friday: 'שישי',
        saturday: 'שבת',

        // Page titles
        pageTitles: {
            '/': 'לוח בקרה',
            '/fields': 'ניהול שדות',
            '/fields/new': 'שדה חדש',
            '/crops': 'ניהול גידולים',
            '/crops/new': 'גידול חדש',
            '/operations': 'פעולות חקלאיות',
            '/sheep': 'ניהול עדר',
            '/vaccinations': 'חיסונים',
            '/treatments': 'טיפולים רפואיים',
            '/births': 'לידות',
            '/water': 'ניהול מים חכם',
            '/water/readings': 'קריאות מים',
            '/water/predictions': 'תחזיות AI',
            '/water/anomalies': 'חריגות',
        }
    },
    en: {
        // Layout & Navigation
        appName: 'Farm Manager',
        smartFarm: 'Smart Farm Management',
        main: 'Main',
        dashboard: 'Dashboard',
        fieldsAndCrops: 'Fields & Crops',
        fields: 'Fields',
        crops: 'Crops',
        agriculturalOps: 'Agricultural Operations',
        sheepFlock: 'Sheep Flock',
        sheep: 'Sheep',
        vaccinations: 'Vaccinations',
        medicalTreatments: 'Medical Treatments',
        births: 'Births',
        waterAI: 'Water Management - AI',
        waterOverview: 'Water Overview',
        waterReadings: 'Water Readings',
        aiPredictions: 'AI Predictions',
        anomalies: 'Anomalies',
        admin: 'Admin',
        farmManager: 'Farm Manager',
        employee: 'Employee',
        user: 'User',
        logout: 'Logout',
        lightMode: 'Light Mode',
        darkMode: 'Dark Mode',

        // Dashboard
        hello: 'Hello',
        farmer: 'Farmer',
        dashboardSummary: "Here's your farm status summary for today",
        totalFields: 'Fields',
        active: 'Active',
        growing: 'Growing',
        waterThisMonth: 'M³ Water This Month',
        openAnomalies: 'Open Anomalies',
        upcomingVacc: 'Upcoming Vaccinations',
        waterTrend30: 'Water Consumption Trend (Last 30 Days)',
        details: 'Details',
        flockHealth: 'Flock Health Status',
        healthy: 'Healthy',
        sick: 'Sick',
        pregnant: 'Pregnant',
        recentOps: 'Recent Operations',
        all: 'All',
        date: 'Date',
        field: 'Field',
        opType: 'Operation Type',
        status: 'Status',
        planting: 'Planting',
        harvesting: 'Harvesting',
        fertilizing: 'Fertilizing',
        spraying: 'Spraying',
        irrigation: 'Irrigation',
        plowing: 'Plowing',
        weeding: 'Weeding',
        completed: 'Completed',
        noRecentOps: 'No recent operations',
        alerts: 'Alerts',
        upcomingVaccAlert: 'Upcoming Vaccination',
        sheepTag: 'Sheep',
        sickSheep: 'Sick Sheep',
        sickSheepDesc: 'Require veterinary care and check-up',
        waterAnomalies: 'Water Anomalies',
        waterAnomaliesDesc: 'Abnormal water consumption needs investigation',
        pregnantSheep: 'Pregnant Sheep',
        pregnantDesc: 'Regular monitoring required',
        noAlerts: 'No new alerts',
        waterConsumption: 'Water Consumption (M³)',

        // Weather
        currentWeather: 'Current Weather',
        temperature: 'Temperature',
        humidity: 'Humidity',
        wind: 'Wind',
        rain: 'Rain',
        feelsLike: 'Feels Like',
        noWeatherData: 'No weather data',

        // Water Dashboard
        smartWaterMgmt: 'Smart Water Management',
        aiWaterSystem: 'Advanced AI system for optimizing farm water consumption',
        aiEnabled: 'AI Enabled',
        totalConsumption: 'Total Consumption (M³)',
        minimum: 'Minimum',
        maximum: 'Maximum',
        avgPerReading: 'Average Per Reading',
        readings: 'Readings',
        openAnomaliesCount: 'Open Anomalies',
        outOf: 'out of',
        total: 'total',
        expectedSavings: 'Expected Savings',
        withAIPredictions: 'Using AI Predictions',
        waterTrend: 'Water Consumption Trend',
        last30Readings: 'Last 30 Readings',
        allReadings: 'All Readings',
        anomalyDistribution: 'Anomaly Distribution',
        anomaliesDetected: 'Anomalies Detected',
        noData: 'No data to display',
        noAnomalies: 'No anomalies',
        weeklyPattern: 'Weekly Consumption Pattern',
        avgByDay: 'Average consumption by day',
        aiInsights: 'AI Insights',
        autoAnalysis: 'Automatic Analysis',
        leadingAlgo: 'Leading Algorithm',
        confidenceLevel: 'Confidence Level',
        avgConsumption: 'Average Consumption',
        analyzedReadings: 'readings analyzed',
        anomaliesNeedAttention: 'anomalies need attention',
        checkAnomalies: 'Check and resolve anomalies',
        potentialSavings: 'Potential Savings',
        basedOnAI: 'Based on AI predictions',
        manageReadings: 'Manage meter readings',
        smartAlgorithms: '3 smart algorithms',
        allOk: 'All clear!',
        openAnomaliesText: 'open anomalies',
        latestPredictions: 'Latest Predictions',
        aiWaterPredictions: 'AI Water Consumption Predictions',
        allPredictions: 'All Predictions',
        confidence: 'confidence',
        cubicMeters: 'M³',
        highConsumption: 'High Consumption',
        lowConsumption: 'Low Consumption',
        leakSuspected: 'Leak Suspected',
        sensorError: 'Sensor Error',
        avgDailyConsumption: 'Avg Daily Consumption',
        sunday: 'Sunday',
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        saturday: 'Saturday',

        // Page titles
        pageTitles: {
            '/': 'Dashboard',
            '/fields': 'Field Management',
            '/fields/new': 'New Field',
            '/crops': 'Crop Management',
            '/crops/new': 'New Crop',
            '/operations': 'Agricultural Operations',
            '/sheep': 'Flock Management',
            '/vaccinations': 'Vaccinations',
            '/treatments': 'Medical Treatments',
            '/births': 'Births',
            '/water': 'Smart Water Management',
            '/water/readings': 'Water Readings',
            '/water/predictions': 'AI Predictions',
            '/water/anomalies': 'Anomalies',
        }
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        return localStorage.getItem('language') || 'he';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.setAttribute('dir', language === 'he' ? 'rtl' : 'ltr');
        document.documentElement.setAttribute('lang', language);
    }, [language]);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'he' ? 'en' : 'he');
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['he']?.[key] || key;
    };

    const isRTL = language === 'he';

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL, translations: translations[language] }}>
            {children}
        </LanguageContext.Provider>
    );
};
